### PR TITLE
Bump dependabot definition to v2 and ignore Guava

### PR DESCRIPTION
**Pull request by rantoniuk**
Ref: #121

### CODE REVIEW

**Comment by warden** [comment]
@raul-arabaolaza it seems that after last two merges the pipeline fails because of disk space.
Are you aware or should I open an INFRA ticket? 

```
buildtriggerbadge:2.10 tests success on JDK8

[2020-10-19T14:45:13.162Z] 
[2020-10-19T14:45:13.162Z] DKMS: install completed.
[2020-10-19T14:45:13.162Z] Setting up linux-headers-4.9.0-13-amd64 (4.9.228-1) ...
[2020-10-19T14:45:13.544Z] Setting up linux-headers-amd64 (4.9+80+deb9u11) ...
[2020-10-19T14:45:13.544Z] Processing triggers for libc-bin (2.24-11+deb9u4) ...
[2020-10-19T14:45:13.544Z] Processing triggers for systemd (232-25+deb9u12) ...
[2020-10-19T14:45:16.904Z] Error processing tar file(exit status 1): write /usr/bin/dockerd: no space left on device
[2020-10-19T14:45:16.904Z] Makefile:31: recipe for target 'docker' failed
[2020-10-19T14:45:16.904Z] make: *** [docker] Error 1
script returned exit code 2
```

**Comment by warden** [comment]
@raul-arabaolaza ping 🙏

**Comment by raul-arabaolaza** [comment]
Sorry, no,I am not aware,feel free to open any INFRA issue, I may have commit rights, but my time here is quite limited and this repo was not receiving a lot of atention in the past, I will schedule a bit of daily time starting tomorrow to review PRs here

**Review by raul-arabaolaza — APPROVED** [review]

**Comment by warden** [comment]
@raul-arabaolaza there were no source code changes in this PR and so the failures are unrelated, thus I feel this can be merged safely.

**Comment by jglick** [comment]
#263?

**Comment by olamy** [comment]
already done

**Comment by jglick** [comment]
Well, not the Guava part I guess, but as in https://github.com/jenkinsci/plugin-compat-tester/pull/319#issuecomment-976775499 we can deal with these as they come up.

**Pull request closed without merging**
