### PR TITLE
Hack for io.jenkins.configuration-as-code:test-harness

### PR DESCRIPTION
**Pull request by jglick**
Same as #261 but with whitespace cleaned up. Apparently needed for `bom` though I do not know the details.

If we at least get an incremental deployment from this, #261 and #275 could be closed.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by jglick** [comment]
Need to get this updated, and then #299 verified in `bom`.

**Review by raul-arabaolaza — APPROVED** [review]

**Review by jetersen — APPROVED** [review]

**Comment by jetersen** [comment]
https://ci.jenkins.io/blue/organizations/jenkins/jenkinsci-libraries%2Fplugin-compat-tester/detail/PR-276/10/pipeline/167#step-168-log-863

```
[2021-09-28T10:36:42.697Z] [ERROR] Failed to execute goal on project artifact-manager-s3: Could not resolve dependencies for project io.jenkins.plugins:artifact-manager-s3:hpi:1.6: Could not find artifact io.jenkins.configuration-as-code:test-harness:jar:1.20 in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) -> [Help 1]
```

**Comment by jglick** [comment]
Still

```
[ERROR] Failed to execute goal on project artifact-manager-s3: Could not resolve dependencies for project io.jenkins.plugins:artifact-manager-s3:hpi:1.15: Could not find artifact io.jenkins.configuration-as-code:test-harness:jar:1.20 in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/)
```

**Comment by jglick** [comment]
Trying to reproduce in a more development-friendly mode than the Docker IT, so far without success (running tests normally):

```bash
mvn -f plugins-compat-tester-cli -Dexec.vmArgs= '-Dexec.args=${exec.vmArgs} -classpath %classpath ${exec.mainClass} ${exec.appArgs}' '-Dexec.appArgs=-overridenPlugins io.jenkins:configuration-as-code=1.20 -includePlugins artifact-manager-s3 -reportFile /tmp/pct/report.xml -workDirectory /tmp/pct' -Dexec.mainClass=org.jenkins.tools.test.PluginCompatTesterCli -Dexec.executable=$(which java) exec:exec
```

This does

```diff
     <dependency> 
       <groupId>io.jenkins</groupId>  
       <artifactId>configuration-as-code</artifactId>  
       <scope>test</scope>  
+      <version>1.20</version> 
     </dependency>  
```

as expected. However it also does this, which is clearly wrong:

```diff
+    <dependency> 
+      <groupId>io.jenkins</groupId>  
+      <artifactId>configuration-as-code</artifactId>  
+      <version>1.20</version> 
+    </dependency>  
```

And this (twice!):

```diff
+    <dependency> 
+      <groupId>io.jenkins.configuration-as-code</groupId>  
+      <artifactId>test-harness</artifactId>  
+      <version>1.53</version>  
+      <scope>test</scope> 
+    </dependency>  
```

PCT is such a train wreck…

**Comment by jglick** [comment]
Will try merging with `master` to pick up #295 etc.

**Comment by timja** [comment]
It's already merged

**Comment by jglick** [comment]
Oh right, I get thrown off guard when other people push to my PRs…

**Comment by jglick** [comment]
> Even without my patch, PCT is wrong

Still true after merging `master`. Somehow it did not matter fur purposes of this IT.

**Comment by jglick** [comment]
@timja do you even remember at this point what fails in `bom` without this patch?

**Comment by timja** [comment]
> @timja do you even remember at this point what fails in `bom` without this patch?

no this was a long time ago

**Comment by jglick** [comment]
Rather than merging in #341, it may be cleaner to file a separate draft PR combining the two just to get an incremental deployment.

**Comment by timja** [comment]
> Rather than merging in #341, it may be cleaner to file a separate draft PR combining the two just to get an incremental deployment.

Possibly, does this version actually work though or is there stuff from master that needs backing out in this PR?

**Comment by jglick** [comment]
> is there stuff from master that needs backing out

Uh…not sure. Should be tracked in https://github.com/jenkinsci/bom/issues/657.

**Comment by timja** [comment]
I’ll try it out tomorrow unless you happen to have time :)

**Comment by timja** [comment]
> Need to get this updated, and then #299 verified in `bom`.

causes bom to fail in injected test which we normally ignore failures in

**Comment by jglick** [comment]
Presumed obsolete after https://github.com/jenkinsci/bom/pull/1336.

**Pull request closed without merging**
