### PR TITLE
[JENKINS-57935] - Always poll the Update Center for plugin Group IDs when building WARs with plugins

### PR DESCRIPTION
**Pull request by oleg-nenashev**
See https://issues.jenkins-ci.org/browse/JENKINS-57935 . Before the fix PCT was not trying to resolve Group  IDs from the update center when there were bundled plugins. It is critical for some optional dependencies which are not usually bundled.

The change should cause no regressions, because groupIDs from WAR will be still a priority

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@batmat creation of the integration test requires a Custom WAR to be produced and included into the test. So far we do not have any official distributions for such custom WARs in the Jenkins community, and it would be a significant task to create one. 

Although I agree with having integration tests, I suggest detaching it to a separate task

**Comment by oleg-nenashev** [comment]
```
Caused by: java.io.IOException: Branch API Plugin version 2.0.21 failed to load.
[2019-06-10T14:30:21.592Z]  - SCM API Plugin version 2.2.6 is older than required. To fix, install version 2.2.7 or later.
[2019-06-10T14:30:21.592Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:821)
[2019-06-10T14:30:21.592Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
[2019-06-10T14:30:21.592Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2019-06-10T14:30:21.592Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2019-06-10T14:30:21.592Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
[2019-06-10T14:30:21.592Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2019-06-10T14:30:21.592Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
[2019-06-10T14:30:21.592Z] 	... 3 more
```

On-demand plugin installation tests are fun

**Comment by oleg-nenashev** [comment]
Uh oh. Will investigate. This is exactly what I was fixing (and it worked on my machine)

```
[2019-06-11T10:12:38.386Z] [INFO] ------------------------------------------------------------------------

[2019-06-11T10:12:38.386Z] [INFO] BUILD FAILURE

[2019-06-11T10:12:38.386Z] [INFO] ------------------------------------------------------------------------

[2019-06-11T10:12:38.386Z] [INFO] Total time:  11.014 s

[2019-06-11T10:12:38.386Z] [INFO] Finished at: 2019-06-11T10:12:38Z

[2019-06-11T10:12:38.386Z] [INFO] ------------------------------------------------------------------------

[2019-06-11T10:12:38.386Z] [ERROR] Failed to execute goal on project artifact-manager-s3: Could not resolve dependencies for project io.jenkins.plugins:artifact-manager-s3:hpi:1.6: Could not find artifact org.jenkins-ci.plugins:configuration-as-code:jar:1.20 in azure-incrementals (https://repo.azure.jenkins.io/incrementals/) -> [Help 1]

[2019-06-11T10:12:38.386Z] [ERROR] 

[2019-06-11T10:12:38.386Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[2019-06-11T10:12:38.386Z] [ERROR] Re-run Maven using the -X switch to 
[2019-06-11T10:12:38.386Z] [ERROR] 

[2019-06-11T10:12:38.386Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:

[2019-06-11T10:12:38.386Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

[2019-06-11T10:12:38.386Z] succeeded artifactIds: []

[2019-06-11T10:12:39.758Z] Exception in thread "main" hudson.AbortException: Execution was aborted due to the failure in a plugin test (-failOnerror is set)

[2019-06-11T10:12:39.758Z] 	at org.jenkins.tools.test.PluginCompatTester.testPlugins(PluginCompatTester.java:360)

```

**Comment by oleg-nenashev** [comment]
Now it somehow starts with old plugins, CWP does not trace it on its own (known issue)

```
[2019-06-11T14:37:54.649Z] Jun 11, 2019 2:37:54 PM jenkins.InitReactorRunner$1 onAttained
[2019-06-11T14:37:54.649Z] INFO: Listed all plugins
[2019-06-11T14:37:54.649Z] Jun 11, 2019 2:37:54 PM jenkins.InitReactorRunner$1 onTaskFailed
[2019-06-11T14:37:54.649Z] SEVERE: Failed Loading plugin Pipeline: Multibranch v2.21 (workflow-multibranch)
[2019-06-11T14:37:54.649Z] java.io.IOException: Pipeline: Multibranch version 2.21 failed to load.
[2019-06-11T14:37:54.649Z]  - Pipeline: Job version 2.15 is older than required. To fix, install version 2.21 or later.
[2019-06-11T14:37:54.649Z]  - Pipeline: Groovy version 2.46 is older than required. To fix, install version 2.53 or later.
[2019-06-11T14:37:54.649Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:821)
[2019-06-11T14:37:54.649Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2019-06-11T14:37:54.649Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
[2019-06-11T14:37:54.649Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-11T14:37:54.649Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-11T14:37:54.649Z] 	at java.lang.Thread.run(Thread.java:748)
[2019-06-11T14:37:54.649Z] 
[2019-06-11T14:37:54.649Z] Jun 11, 2019 2:37:54 PM jenkins.InitReactorRunner$1 onTaskFailed
[2019-06-11T14:37:54.649Z] SEVERE: Failed Loading plugin Jenkins JSch dependency plugin v0.1.54.2 (jsch)
[2019-06-11T14:37:54.649Z] java.io.IOException: Jenkins JSch dependency plugin version 0.1.54.2 failed to load.
[2019-06-11T14:37:54.649Z]  - SSH Credentials Plugin version 1.11 is older than required. To fix, install version 1.13 or later.
[2019-06-11T14:37:54.649Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:821)
[2019-06-11T14:37:54.649Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2019-06-11T14:37:54.649Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
[2019-06-11T14:37:54.649Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-11T14:37:54.649Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-11T14:37:54.649Z] 	at java.lang.Thread.run(Thread.java:748)
[2019-06-11T14:37:54.649Z] 
[2019-06-11T14:37:54.649Z] Jun 11, 2019 2:37:54 PM jenkins.InitReactorRunner$1 onTaskFailed
[2019-06-11T14:37:54.649Z] SEVERE: Failed Loading plugin Pipeline: Nodes and Processes v2.30 (workflow-durable-task-step)
[2019-06-11T14:37:54.649Z] java.io.IOException: Pipeline: Nodes and Processes version 2.30 failed to load.
[2019-06-11T14:37:54.649Z]  - Pipeline: Supporting APIs version 2.17 is older than required. To fix, install version 3.1 or later.
[2019-06-11T14:37:54.649Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:821)
[2019-06-11T14:37:54.649Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2019-06-11T14:37:54.649Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2019-06-11T14:37:54.649Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
[2019-06-11T14:37:54.649Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-11T14:37:54.649Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-11T14:37:54.649Z] 	at java.lang.Thread.run(Thread.java:748)
[2019-06-11T14:37:54.649Z] 
[2019-06-11T14:37:54.649Z] Jun 11, 2019 2:37:54 PM jenkins.InitReactorRunner$1 onTaskFailed
[2019-06-11T14:37:54.649Z] SEVERE: Failed Loading plugin Jenkins Git client plugin v3.0.0-rc (git-client)
[2019-06-11T14:37:54.649Z] java.io.IOException: Jenkins Git client plugin version 3.0.0-rc failed to load.
[2019-06-11T14:37:54.649Z]  - Jenkins JSch dependency plugin version 0.1.54.2 failed to load. Fix this plugin first.
[2019-06-11T14:37:54.649Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:821)
[2019-06-11T14:37:54.649Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2019-06-11T14:37:54.907Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
[2019-06-11T14:37:54.907Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-11T14:37:54.907Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-11T14:37:54.907Z] 	at java.lang.Thread.run(Thread.java:748)
[2019-06-11T14:37:54.907Z] 
[2019-06-11T14:37:54.907Z] Jun 11, 2019 2:37:54 PM jenkins.InitReactorRunner$1 onTaskFailed
[2019-06-11T14:37:54.907Z] SEVERE: Failed Loading plugin Jenkins Git plugin v4.0.0-rc (git)
[2019-06-11T14:37:54.907Z] java.io.IOException: Jenkins Git plugin version 4.0.0-rc failed to load.
[2019-06-11T14:37:54.907Z]  - Jenkins Git client plugin version 3.0.0-rc failed to load. Fix this plugin first.
[2019-06-11T14:37:54.907Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:821)
[2019-06-11T14:37:54.907Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2019-06-11T14:37:54.907Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
[2019-06-11T14:37:54.907Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-11T14:37:54.907Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-11T14:37:54.907Z] 	at java.lang.Thread.run(Thread.java:748)
[2019-06-11T14:37:54.907Z] 
[2019-06-11T14:37:54.907Z] Jun 11, 2019 2:37:54 PM jenkins.InitReactorRunner$1 onTaskFailed
[2019-06-11T14:37:54.907Z] SEVERE: Failed Loading plugin Jenkins SSH Slaves plugin v1.29.4 (ssh-slaves)
[2019-06-11T14:37:54.907Z] java.io.IOException: Jenkins SSH Slaves plugin version 1.29.4 failed to load.
[2019-06-11T14:37:54.907Z]  - SSH Credentials Plugin version 1.11 is older than required. To fix, install version 1.14 or later.
[2019-06-11T14:37:54.907Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:821)
[2019-06-11T14:37:54.907Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2019-06-11T14:37:54.907Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2019-06-11T14:37:54.907Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
[2019-06-11T14:37:54.907Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-11T14:37:54.907Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-11T14:37:54.907Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by oleg-nenashev** [comment]
WithPlugin tests are killing me

```
[2019-06-17T14:57:00.955Z] [ERROR] testPluginActive(org.jvnet.hudson.test.PluginAutomaticTestBuilder$OtherTests)  Time elapsed: 0.012 s  <<< ERROR!
[2019-06-17T14:57:00.955Z] java.lang.Error: Plugin workflow-multibranch failed to start
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.test.PluginAutomaticTestBuilder$OtherTests.testPluginActive(PluginAutomaticTestBuilder.java:99)
[2019-06-17T14:57:00.955Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-06-17T14:57:00.955Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-06-17T14:57:00.955Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-06-17T14:57:00.955Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2019-06-17T14:57:00.955Z] 	at junit.framework.TestCase.runTest(TestCase.java:176)
[2019-06-17T14:57:00.955Z] 	at junit.framework.TestCase.runBare(TestCase.java:141)
[2019-06-17T14:57:00.955Z] 	at junit.framework.TestResult$1.protect(TestResult.java:122)
[2019-06-17T14:57:00.955Z] 	at junit.framework.TestResult.runProtected(TestResult.java:142)
[2019-06-17T14:57:00.955Z] 	at junit.framework.TestResult.run(TestResult.java:125)
[2019-06-17T14:57:00.955Z] 	at junit.framework.TestCase.run(TestCase.java:129)
[2019-06-17T14:57:00.955Z] 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
[2019-06-17T14:57:00.955Z] 	at junit.framework.TestSuite.run(TestSuite.java:247)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.test.junit.GroupedTest.runGroupedTests(GroupedTest.java:67)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.doTests(JellyTestSuiteBuilder.java:152)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.access$100(JellyTestSuiteBuilder.java:138)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite$2.call(JellyTestSuiteBuilder.java:160)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.test.HudsonTestCase$WebClient$5.run(HudsonTestCase.java:1514)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.test.ClosureExecuterAction.doIndex(ClosureExecuterAction.java:53)
[2019-06-17T14:57:00.955Z] 	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.IndexDispatcher.dispatch(IndexDispatcher.java:27)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:458)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
[2019-06-17T14:57:00.955Z] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
[2019-06-17T14:57:00.955Z] 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
[2019-06-17T14:57:00.955Z] 	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
[2019-06-17T14:57:00.955Z] 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
[2019-06-17T14:57:00.955Z] 	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
[2019-06-17T14:57:00.955Z] 	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:105)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
[2019-06-17T14:57:00.955Z] 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
[2019-06-17T14:57:00.955Z] 	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
[2019-06-17T14:57:00.955Z] 	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
[2019-06-17T14:57:00.955Z] 	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
[2019-06-17T14:57:00.955Z] 	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.Server.handle(Server.java:564)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
[2019-06-17T14:57:00.955Z] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
[2019-06-17T14:57:00.955Z] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2019-06-17T14:57:00.955Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2019-06-17T14:57:00.955Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2019-06-17T14:57:00.955Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2019-06-17T14:57:00.955Z] 	at java.lang.Thread.run(Thread.java:748)
[2019-06-17T14:57:00.955Z] Caused by: java.io.IOException: Pipeline: Multibranch version 2.21 failed to load.
[2019-06-17T14:57:00.955Z]  - Pipeline: Job version 2.15 is older than required. To fix, install version 2.21 or later.
[2019-06-17T14:57:00.955Z]  - Pipeline: Groovy version 2.46 is older than required. To fix, install version 2.53 or later.
[2019-06-17T14:57:00.955Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:821)
[2019-06-17T14:57:00.955Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:544)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2019-06-17T14:57:00.955Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1096)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2019-06-17T14:57:00.955Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
```

**Comment by oleg-nenashev** [comment]
In the test...

```
[2019-06-18T12:46:24.184Z] Caused by: java.io.IOException: Display URL API version 0.2 failed to load.
[2019-06-18T12:46:24.184Z]  - JUnit Plugin version 1.2 is older than required. To fix, install version 1.3 or later.
```

Something went wrong, not sure what

**Comment by oleg-nenashev** [comment]
```
[2019-06-18T13:25:31.461Z] Caused by: java.io.IOException: Display URL API version 0.2 failed to load.
[2019-06-18T13:25:31.462Z]  - JUnit Plugin version 1.2 is older than required. To fix, install version 1.3 or later.
```

Any ideas why it could happen @raul-arabaolaza . It there any code which may downgrade a version from the bundle?

**Comment by varyvol** [comment]
Closing in favor of #169

**Pull request merged**
