### PR TITLE
Convert connectionUrl from git@github.com:jenkinsci to git://github.c…

### PR DESCRIPTION
**Pull request by rsandell**
…om/jenkinsci

At least dockerhub-notification plugin has this bad url

@reviewbybees

### CODE REVIEW

**Comment by kwhetstone** [comment]
:bee: Makes sense; hopefully this helps find some other plugins that failed to build.

**Comment by jglick** [comment]
:bug: for failure to add a test case to `ScmConnectionSpecialCasesTest`.

**Comment by jglick** [comment]
Or rather to unignore `shouldGitAtGithubReplaceByGitProtocol`. Presumably there was some reason it was suppressed originally. Everything in @jenkinsci should be public anyway, but plugins in other organizations cannot use `git` protocol.

What is the actual problem you are trying to solve here, anyway? You can access a public repository using `ssh` protocol without having any special permissions.

**Comment by jglick** [comment]
Specifically I think I intentionally disabled this transformation in dbcdbac42fd2d096ec4888a822bf8810abd20d26.

**Comment by rsandell** [comment]
The connection url that dockerhub-notification plugin has specified is made in a way that the checkout is performed with the git protocol using a ssh'ish url (except for the scema) and fails to do it.

**Comment by rsandell** [comment]
Yes the old disabled transformation was to remove the username from any guthub.com url, and I agree with removing that.
My change should only transform urls to the jenkinsci org where all plugins should be public while repositories in other orgs might not and so the transformation leaves those alone.

**Comment by jglick** [comment]
How specifically did it fail to check out `dockerhub-notification-plugin`?

**Comment by jglick** [comment]
I guess you mean that it was actually a malformed URL in that case? If so, :bee: but please file a PR for the plugin to fix its POM.

**Comment by tfennelly** [comment]
:bee:

**Comment by rsandell** [comment]
@reviewbybees done

**Comment by rsandell** [comment]
Yes the url can be considered malformed _(but the maven release process did work with that url)_ And my next step is to change it in th eplugin, but I don't feel it appropriate to make a new release with just pom changes so the compat tester still needs to handle that type of malformation I guess.

**Pull request merged**
