### PR TITLE
Use warnings-ng instead of deprecated findbugs

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
Recreates #259 per @bmunozm request so it can be tested by the PR Builder, I have already review the changes and look safe to run

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
I would recommend moving to the Warnings NG plugin. I do not think we will keep FindBugs plugin on the instance for long time

**Review by bmunozm — APPROVED** [review]

**Comment by raul-arabaolaza** [comment]
I have removed the `findBugs` call and replaced with (I believe) warnings-ng, let's see if I have done it properly

**Comment by raul-arabaolaza** [comment]
Failure caused by infra issue 

`There is not enough space on the disk`

Closing and reopening later

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Please use a single command to avoid performance overheads. Example: https://github.com/jenkinsci/custom-war-packager/blob/master/Jenkinsfile#L46-L49

**Comment by raul-arabaolaza** [comment]
I made a mistake, ok, I need to give a bit of extra work here, please do not merge, is not ready yet

**Comment by timja** [comment]
@raul-arabaolaza what's wrong with this? it seems fine

**Review by bmunozm — APPROVED** [review]

**Review by jglick — APPROVED** [review]

**Comment by jglick** [comment]
Can this please be merged so that #261 can be deployed and I can fix up https://github.com/jenkinsci/bom/pull/294/commits/7322eb7556ac970a2979ed3af7278b58315bae99?

**Comment by raul-arabaolaza** [comment]
Sorry, my fault

**Pull request merged**
