### PR TITLE
Fail fast when attempting to run PCT against a release with a missing or nondeterministic tag

### PR DESCRIPTION
**Pull request by basil**
A CloudBees employed complained about PCT, writing

> There is no way the PCT job could actually check out this revision of sources—that information is not even available in the snapshot that I know of. But it should at least skip running this plugin at all. Fine to mark the plugin as a PCT checkout failure. Just do not pretend to run it, actually checking out something else (`master` apparently).

With this PR we mark such `-SNAPSHOT` plugins as a PCT checkout failure. Note that this covers both regular snapshots and timestamped snapshots.

To test this I deployed https://repo.jenkins-ci.org/artifactory/snapshots/org/jenkins-ci/plugins/text-finder/1.24-SNAPSHOT/ and updated `jenkinsci/bom` with

```xml
diff --git a/bom-weekly/pom.xml b/bom-weekly/pom.xml
index c91af8d..c093a49 100644
--- a/bom-weekly/pom.xml
+++ b/bom-weekly/pom.xml
@@ -557,7 +557,7 @@
             <dependency>
                 <groupId>org.jenkins-ci.plugins</groupId>
                 <artifactId>text-finder</artifactId>
-                <version>1.23</version>
+                <version>1.24-20230322.225534-1</version>
             </dependency>
             <dependency>
                 <groupId>org.jenkins-ci.plugins</groupId>
diff --git a/sample-plugin/pom.xml b/sample-plugin/pom.xml
index 20da6a7..69e473c 100644
--- a/sample-plugin/pom.xml
+++ b/sample-plugin/pom.xml
@@ -592,6 +592,13 @@
             <id>repo.jenkins-ci.org</id>
             <url>https://repo.jenkins-ci.org/public/</url>
         </repository>
+        <repository>
+          <snapshots>
+            <enabled>true</enabled>
+          </snapshots>
+          <id>snapshots</id>
+          <url>https://repo.jenkins-ci.org/snapshots/</url>
+        </repository>
     </repositories>
     <pluginRepositories>
         <pluginRepository>
```

I then ran `PLUGINS=text-finder TEST=InjectedTest bash local-test.sh` before and after this PR. Before this PR, the test passed but checked out `master` not the timestamped snapshot requested. After this PR, PCT failed as expected.

### CODE REVIEW

**Comment by jglick** [comment]
> this covers both regular snapshots and timestamped snapshots

It should be limited to plain snapshots, or if that is not straightforward, not done at all: PCT _can_ test a timestamped snapshot if you manually adjust the `scm` section of the deployed POM to point to the associated commit. (This only works for tests of the snapshotted plugin itself, not any other plugin which might depend upon it.)

Possibly it would suffice to see if the `tag` is still set to `HEAD`, meaning no deterministic version.

**Comment by basil** [comment]
> Possibly it would suffice

It does not: https://repo.jenkins-ci.org/artifactory/snapshots/org/jenkins-ci/plugins/text-finder/1.24-SNAPSHOT/text-finder-1.24-20230322.225534-1.pom

> It should be limited to plain snapshots, or if that is not straightforward, not done at all

If you do not want this to be done at all, I will close this PR and I will close the internal ticket you filed as `WONTFIX`.

**Review by jglick — APPROVED** [review]
Looks right.

**Comment by basil** [comment]
Could move this out of a hook into the main class, but keeping it in a hook has the nice property that it can be disabled if necessary. No strong feeling either way.

**Comment by basil** [comment]
Oh I keep forgetting to file these from `origin` instead of my fork, which James tells me he needs. Closing in favor of #499.

**Pull request closed without merging**
