### PR TITLE
[JENKINS-55147] - Automate analysis of JVM crashes in PCT Docker images

### PR DESCRIPTION
**Pull request by oleg-nenashev**
During testing of plugins with Java 11, we have discovered several case when Maven Surefire just crashes with Java 11 (e.g. JENKINS-55146 or JENKINS-55097).

In the current state the errors just get suppressed, and you need to run manually in Docker containers to reproduce them.

It would be great if there is a way to get crashdumps in the build log when it happens. Ideally we need to do it as a part of the PCT execution engine, but having something for Docker is a good start

Output example:

```
+ [[ 1 != \0 ]]
+ echo 'ERROR: PCT failed with code 1. Will check for Maven Surefire dumps if it crashed'
ERROR: PCT failed with code 1. Will check for Maven Surefire dumps if it crashed
++ find /pct/tmp/work/script-security/target/surefire-reports/2018-12-13T00-30-45_764-jvmRun1.dumpstream
+ dumpFiles=/pct/tmp/work/script-security/target/surefire-reports/2018-12-13T00-30-45_764-jvmRun1.dumpstream
+ '[' -n /pct/tmp/work/script-security/target/surefire-reports/2018-12-13T00-30-45_764-jvmRun1.dumpstream ']'
+ echo /pct/tmp/work/script-security/target/surefire-reports/2018-12-13T00-30-45_764-jvmRun1.dumpstream
+ read file
+ echo 'Found Maven Surefire dump file: /pct/tmp/work/script-security/target/surefire-reports/2018-12-13T00-30-45_764-jvmRun1.dumpstream'
+ cat /pct/tmp/work/script-security/target/surefire-reports/2018-12-13T00-30-45_764-jvmRun1.dumpstream
Found Maven Surefire dump file: /pct/tmp/work/script-security/target/surefire-reports/2018-12-13T00-30-45_764-jvmRun1.dumpstream
# Created on 2018-12-13T00:30:46.986
Corrupted stdin stream in forked JVM 1. Stream 'Error occurred during initialization of boot layer'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'Error occurred during initialization of boot layer'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:469)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:191)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:158)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:87)
	at java.lang.Thread.run(Thread.java:748)


# Created on 2018-12-13T00:30:46.991
Corrupted stdin stream in forked JVM 1. Stream 'java.lang.module.FindException: Module java.activation not found, required by java.xml.bind'.

+ read file
+ exit 1
```

https://issues.jenkins-ci.org/browse/JENKINS-55147

@jenkinsci/java11-support

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
The code is pretty much useless until https://github.com/jenkinsci/plugin-compat-tester/pull/94 is integrated

**Comment by batmat** [comment]
Now PR build is successful @raul-arabaolaza, let's merge yey? :-) :man_dancing:

**Comment by raul-arabaolaza** [comment]
@batmat Actually I had a great idea about using a CQRS/Event Sourced approach to send real-time JVM statistics to a blockchain based system to be able to see in our phones all the needed information in real time. For that, I only need some time for a small full rewrite of the PCT. I Hope you can understand that is more important than this PR :P

**Comment by raul-arabaolaza** [comment]
And obviously a much better approach :P

**Pull request merged**
